### ISSUE TITLE
Cannot change any of the Manage File Locations folders in dnn 9.1.  So all of our existing records are no longer found giving 404

### ISSUE THREAD

**Issue by jverdes** [juvander/dnnrepository#1]
cannot change the Manage File Locations folders after upgrade to 3.5.8 in dnn 9.1 which is causing all of our existing records to bomb when trying to download them.

**Comment by juvander** [comment]
I don't think that this is compatible with 9.1, too many things changed. And as I don't see upgrade on our environments to 9.x anytime soon, this won't be fixed either.

**Comment by jverdes** [comment]
We had a fix on the 3.5.6 version by going into the database module settings and changed file location setting for the Folder for Approved Files: section.  And this would automatically change the pending and Anonymous locations and everything worked.  It does not do the same in 3.5.8.  Do you happen to know where the pending and anonymous folder location settings are in the tables?

**Comment by juvander** [comment]
Is this location under the root of website? This was changed in this version mainly due to Azure stuff to make transition easier.

Original location is stored in the database as hard path, not relative. Check the value in DB first.

**Comment by jverdes** [comment]
the location is under the website in portal 0
We are not seeing in the database where the values for the Folder for Unapproved Files or Folder for Anonymous Files are being stored.  We did find the Folder for Approved Files value and have made changes.

**Comment by juvander** [comment]
See setting section Manage File Locations (HOST Only)

**Comment by jverdes** [comment]
Yes,  those are the three fields that we can no longer change.

**Comment by juvander** [comment]
There seems to be some exception coming when updating those. Will see if I can find the time to debug it.

**Comment by jverdes** [comment]
Thank you for looking into it.

**Comment by juvander** [comment]
Download release package again and update the installation.

Thing with this is, that original idea was that location cannot be changed (because of the move to Azure), but for this approved folder this settings page was not updated correctly. So now everything is under the repository root folder.
